---
# List of block lists to import from URLs
dns_blocklists_lists:
  # The Basic list is a smaller, less comprehensive variant of the full list, which focussus mainly on Ads, (Mobile) App Ads
  # https://oisd.nl/faq#basic
  - name: oisd-small
    type: adblock
    url: https://small.oisd.nl/rpz # Use the BIND list directly since we use BIND on our servers

  - name: frellwits-swedish-hosts-file
    type: adblock
    url: https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt

  - name: AdguardDNS
    type: adblock
    url: https://v.firebog.net/hosts/AdguardDNS.txt

  - name: blocklist-project
    type: gambling
    url: https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/gambling-nl.txt
  
  - name: firebog-easylist-privacy
    url: https://v.firebog.net/hosts/Easyprivacy.txt
    type: privacy

  - name: windows-spy-blocker-spy
    url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    type: privacy

  - name: perflyst-android-tracking
    url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
    type: privacy

  - name: telemetry-alexa
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/alexa
    type: privacy

  - name: telemetry-apple
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/apple
    type: privacy

  - name: telemetry-huawei
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/huawei
    type: privacy

  - name: telemetry-samsung
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung
    type: privacy
  
  - name: telemetry-sonos
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/sonos
    type: privacy

  - name: telemetry-windows
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/windows
    type: privacy

  - name: telemetry-xiaomi
    url: https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi
    type: privacy

  - name: oisd-nsfw
    url: https://nsfw.oisd.nl/rpz
    type: adult

  - name: mullvad-social-blocklist
    type: social
    content: "{{ lookup('ansible.builtin.file', 'files/social') }}"
