---
# List of URLs per blocklist to remove,
# URLs in these lists get removed if they are ever accidentally
# included in upstream lists.
#
# Example:
#
# dns_blocklists_exclude:
#   - name: adult
#     entries:
#       - last.fm
#       - readly.com
#       - other-non-adult-website.com
#
#   - name: ...
#
dns_blocklists_exclude:
  - name: adblock
    entries: []

  - name: adult
    entries: []
  
  - name: gambling
    entries: []

  - name: privacy 
    entries: []

  - name: social
    entries: []

# List of block lists to import from URLs
dns_blocklists_lists:
  - name: oisd-small
    type: adblock
    url: https://small.oisd.nl/rpz # Use the BIND list directly since we use BIND on our servers

  - name: frellwits-swedish-hosts-file
    type: adblock
    url: https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt

  - name: AdguardDNS
    type: adblock
    url: https://v.firebog.net/hosts/AdguardDNS.txt

  - name: oisd-nsfw
    url: https://nsfw.oisd.nl/rpz
    type: adult

  - name: hagezi-gambling-onlydomains
    type: gambling
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling-onlydomains.txt
  
  - name: hagezi-gambling
    type: gambling
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt
  
  - name: firebog-easylist-privacy
    url: https://v.firebog.net/hosts/Easyprivacy.txt
    type: privacy

  - name: hagezi-tracker-amazon
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.amazon.txt
    type: privacy

  - name: hagezi-tracker-apple
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.apple.txt
    type: privacy

  - name: hagezi-tracker-huawei
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.huawei.txt
    type: privacy

  - name: hagezi-tracker-windows
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.winoffice.txt
    type: privacy

  - name: hagezi-tracker-tiktok-aggressive
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.tiktok.extended.txt
    type: privacy
  
  - name: hagezi-tracker-webos
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.lgwebos.txt
    type: privacy

  - name: hagezi-tracker-vivo
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.vivo.txt
    type: privacy

  - name: hagezi-tracker-oppo
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.oppo-realme.txt
    type: privacy

  - name: hagezi-tracker-xiamomi
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.xiaomi.txt
    type: privacy
  
  - name: mullvad-tracker-blocklist
    type: privacy
    content: "{{ lookup('ansible.builtin.file', 'files/tracker') }}"

  - name: mullvad-social-blocklist
    type: social
    content: "{{ lookup('ansible.builtin.file', 'files/social') }}"
